name: Block PR without label
description: Блокирование мерджа PR, если у него не стоит необходимого лейбла

inputs:
  repo_token:
    description: Токен для gh репозитория
    required: true
  necessary_label:
    description: Лейбл, отсутствие которого блокирует мердж PR
    required: true

runs:
  using: node12
  main: dist/index.js

branding:
  icon: clock
  color: yellow
