
name: Релиз пакетов
description: Релиз пакетов из монорепозитории в npm-gh-registry

inputs:
  branch:
    description: Имя текущей веткп
    required: true
  main_branch:
    description: Имя основной ветки
  gh_user:
    description: Имя пользователя на github
  gh_email:
    description: Почта на github

runs:
  using: node12
  main: dist/index.js
