
name: Release package
description: Release lerna packages to gh registry

inputs:
  branch:
    description: github branch name
    required: true
  main_branch:
    description: github main branch
  gh_user:
    description: github user
  gh_email:
    description: github email

runs:
  using: node12
  main: dist/index.js
