name: Публикация Github-релиза
description: Публикует новый релиз на github с тегом и CHANGELOG

inputs:
  tag:
    description: Имя тега
    required: true
  main_package:
    description: Название основного пакета
    required: true
  changelog:
    description: Новый CHANGELOG
    required: true
  token:
    description: Токен доступа к репозиторию
    required: true

runs:
  using: node12
  main: dist/index.js

branding:
  icon: github
